### ISSUE TITLE
discussion with kate and leigh

### ISSUE THREAD

**Issue by anjiemerchant** [new-kids-on-the-blockchain/block-and-mortar#11]

**Comment by k-vosswinkel** [comment]
- What is a realistic MVP
- How are we handling users vs. profiles? Handling private data?
- Do we need an admin login for our MVP?
- If the MVP of the app is to simply exchange goods through blockchain, does our user flow make sense, or have we over-complicated things? How do we start simple and build out?
- Front-end state; what are we keeping there?

**Comment by k-vosswinkel** [comment]
How are we handling users vs. profiles? Handling private data?

**Comment by k-vosswinkel** [comment]
Do we need an admin login for our MVP?
